spring:
  data:
    mongodb:
      database: "data-analysis-system"
application:
  data:
    manipulation:
      parsing:
        splitter:
          row-data-splitter: 'รง'
          item-splitter: '-'
          item-list-splitter: ','
          item-starter: '['
          item-finisher: ']'
        index:
          salesman:
            cpf: 1
            name: 2
            salary: 3
          customer:
            cnpj: 1
            name: 2
            business-area: 3
          sale:
            id: 1
            item: 2
            name-salesman: 3
          item:
            id: 0
            quantity: 1
            price: 2
    io:
      extension:
        input-file-extension: .dat
        output-file-extension: .done.dat
      directory:
        input: ${user.home}/data/in
        output: ${user.home}/data/out
      file-name:
        report: report